In [1]:
import numpy as np
import pandas as pd
from database import DB_CONN, UpdateOne

In [2]:
excel_name = 'data/stock_basic.xlsx'

In [3]:
df_2015 = pd.read_excel(excel_name, 1, header=0, index_col=[0,1], dtype={})

In [4]:
df_2015.head()

             2015-01-05 2015-01-06 2015-01-07 2015-01-08 2015-01-09  \
1 平安银行 是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
2 万科A  是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
4 国农科技 是否ST           否          否          否          否          否

             2015-01-12 2015-01-13 2015-01-14 2015-01-15 2015-01-16  \
1 平安银行 是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
2 万科A  是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
4 国农科技 是否ST           否          否          否          否          否

                ...     2015-12-18 2015-12-21 2015-12-22 2015-12-23  \
1 平安银行 是否ST     ...              否          否          否          否
       是否*ST    ...              否          否          否          否
2 万科A  是否ST     ...              否          否          否          否
       是否*ST    ...              否          否          否          否
4 国农科技 是否ST     ...              否          否          否          否

             2015-12-24 2015-12-25 2015-12-28 2015-12-29 2015-12-30 2015-12-31
1 平安银行 是否ST           否          否          否          否          否          否
       是否*ST          否          否          否          否          否          否
2 万科A  是否ST           否          否          否          否          否          否
       是否*ST          否          否          否          否          否          否
4 国农科技 是否ST           否          否          否          否          否          否

[5 rows x 244 columns]

In [62]:
df_test = pd.read_excel('data/test.xlsx', header=0, dtype={'code':str})
df_test = df_test.set_index(['code','state'])
df_test.columns = df_test.columns.astype(np.datetime64)
df_test.columns = df_test.columns.to_period('D')
df_test.columns = df_test.columns.astype('str')

In [63]:
df_test

             2015-01-05 2015-01-06 2015-01-07 2015-01-08 2015-01-09  \
code   state
000001 是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
000002 是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
000004 是否ST           否          否          否          否          否

             2015-01-12 2015-01-13 2015-01-14 2015-01-15 2015-01-16  \
code   state
000001 是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
000002 是否ST           否          否          否          否          否
       是否*ST          否          否          否          否          否
000004 是否ST           否          否          否          否          否

                ...     2015-12-18 2015-12-21 2015-12-22 2015-12-23  \
code   state    ...
000001 是否ST     ...              否          否          否          否
       是否*ST    ...              否          否          否          否
000002 是否ST     ...              否          否          否          否
       是否*ST    ...              否          否          否          否
000004 是否ST     ...              否          否          否          否

             2015-12-24 2015-12-25 2015-12-28 2015-12-29 2015-12-30 2015-12-31
code   state
000001 是否ST           否          否          否          否          否          否
       是否*ST          否          否          否          否          否          否
000002 是否ST           否          否          否          否          否          否
       是否*ST          否          否          否          否          否          否
000004 是否ST           否          否          否          否          否          否

[5 rows x 244 columns]

In [64]:
df_test.xs(['000001'])['2015-01-05']['是否ST']

'否'

In [58]:
df_test.xs(['000001'])['2015-01-05']['是否*ST']

'否'

In [50]:
def is_st(*series):
    flag = False
    for i in series:
        if i == '是':
            flag = True
    return flag

In [51]:
df_test.groupby(by=['code', 'name']).apply(is_st)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().